version: "3"

networks:
  default:
  web:
    external: true

services:
  pipedfrontend:
    image: 1337kavin/piped-frontend:latest@sha256:805371a3aec331ccd27ca793d9bbcb79f50b3aa66cc3aa92c070c5bacc21fcd4
    restart: always
    container_name: pipedfrontend
    depends_on:
      - piped
    entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/api.piped.aosus.link/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
    networks:
      web:

  piped-proxy:
    image: 1337kavin/piped-proxy:latest@sha256:ddff9e9adee8aa931135c69e5e2d0e0495b7c278ef46db9c1109439539cfe825
    container_name: piped-proxy
    restart: always
    environment:
      - UDS=1
    volumes:
      - piped-proxy:/app/socket

  piped:
    image: 1337kavin/piped:latest@sha256:bfff18ceec289374134e8b60bd3f91a29e58121f13b6107407afaaa6f71721a3
    container_name: piped
    restart: always
    configs:
      - source: piped
        target: /app/config.properties
    depends_on:
      - postgres
      
  nginx:
    image: nginx:mainline-alpine@sha256:02ffd439b71d9ea9408e449b568f65c0bbbb94bebd8750f1d80231ab6496008e
    restart: always
    container_name: piped-nginx
    volumes:
      - piped-proxy:/var/run/ytproxy
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
      - source: pipedapi
        target: /etc/nginx/conf.d/pipedapi.conf
      - source: pipedproxy
        target: /etc/nginx/conf.d/pipedproxy.conf
      - source: pipedfrontend
        target: /etc/nginx/conf.d/pipedfrontend.conf
      - source: ytproxy
        target: /etc/nginx/snippets/ytproxy.conf
    depends_on:
      - piped
      - piped-proxy
      - pipedfrontend
    networks:
      - default
      - web

  postgres:
    image: postgres:15.2-alpine@sha256:07ec36ad2d5ab9250f38c8ef749239b662cf15d03c9ddb7167422edbbdf71156
    container_name: piped-postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD

volumes:
  postgres:
  piped-proxy:


configs:
  nginx:
    file: /home/aosus/piped/config/nginx.conf
  pipedapi:
    file: /home/aosus/piped/config/pipedapi.conf
  pipedproxy:
    file: /home/aosus/piped/config/pipedproxy.conf
  pipedfrontend:
    file: /home/aosus/piped/config/pipedfrontend.conf
  ytproxy:
    file: /home/aosus/piped/config/ytproxy.conf
  piped: 
    file: /home/aosus/piped/config.properties