version: "3"

networks:
  default:
  web:
    external: true

services:
  pipedfrontend:
    image: 1337kavin/piped-frontend:latest@sha256:366152fae9e92d82db346a7a01177c931bdbf00dbc345ca6d47b52e5c8533bf6
    restart: always
    container_name: pipedfrontend
    depends_on:
      - piped
    entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/api.piped.aosus.org/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
    networks:
      web:

  piped-proxy:
    image: 1337kavin/piped-proxy:latest@sha256:ac25b01b40abcc1192ff3e96ba10bb06e65bfdc84fc2dd387fe340db1ee08f77
    container_name: piped-proxy
    restart: always
    environment:
      - UDS=1
    volumes:
      - piped-proxy:/app/socket

  piped:
    image: 1337kavin/piped:latest@sha256:db12b719da55bf83983fd23462742020b9127516f817e814c747a7e9a5092870
    container_name: piped
    restart: always
    configs:
      - source: piped
        target: /app/config.properties
    depends_on:
      - postgres
      
  nginx:
    image: nginx:mainline-alpine@sha256:dd2a9179765849767b10e2adde7e10c4ad6b7e4d4846e6b77ec93f080cd2db27
    restart: always
    container_name: piped-nginx
    volumes:
      - piped-proxy:/var/run/ytproxy
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
      - source: pipedapi
        target: /etc/nginx/conf.d/pipedapi.conf
      - source: pipedproxy
        target: /etc/nginx/conf.d/pipedproxy.conf
      - source: pipedfrontend
        target: /etc/nginx/conf.d/pipedfrontend.conf
      - source: ytproxy
        target: /etc/nginx/snippets/ytproxy.conf
    depends_on:
      - piped
      - piped-proxy
      - pipedfrontend
    networks:
      - default
      - web

  postgres:
    image: postgres:15.2-alpine@sha256:07ec36ad2d5ab9250f38c8ef749239b662cf15d03c9ddb7167422edbbdf71156
    container_name: piped-postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD

volumes:
  postgres:
  piped-proxy:


configs:
  nginx:
    file: /home/aosus/piped/config/nginx.conf
  pipedapi:
    file: /home/aosus/piped/config/pipedapi.conf
  pipedproxy:
    file: /home/aosus/piped/config/pipedproxy.conf
  pipedfrontend:
    file: /home/aosus/piped/config/pipedfrontend.conf
  ytproxy:
    file: /home/aosus/piped/config/ytproxy.conf
  piped: 
    file: /home/aosus/piped/config.properties