networks: 
  default:
  web:
    external: true

services:
  plausible_db:
    restart: unless-stopped
    image: postgres:12.16-alpine@sha256:afe2b781d2fac4424271b96b8dcc61bfe751de812b77a168bfa139e8e00676ac
    volumes:
      - /home/aosus/plausible/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD

  plausible_events_db:
    restart: unless-stopped
    image: clickhouse/clickhouse-server:22.12-alpine@sha256:c2abc9bd093328270bb3d0b259ec3b8871306fb6084359d42859ebee433ef0d9
    volumes:
      - /home/aosus/plausible/event-data:/var/lib/clickhouse
    configs:
      - source: clickhouse-config
        target: /etc/clickhouse-server/config.d/logging.xml
      - source: clickhouse-user-config
        target: /etc/clickhouse-server/users.d/logging.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    restart: unless-stopped
    image: plausible/analytics:v2.0.0@sha256:5bf2057948e1d5d12ef61f446c4945a336d3bcdf9b96293a1d6fc275f3c56eb5
    container_name: plausible
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    expose:
      - 8000
    depends_on:
      - plausible_db
      - plausible_events_db
    # ports:
      # - 8004:8000
    environment:
      - BASE_URL=https://pa.aosus.org
      - DISALBLE_REGISTRATION=true
      - MAILER_EMAI=plausible@services.aosus.org
      - SMTP_HOST_ADDR=smtp.eu.mailgun.org
      - SMTP_HOST_PORT=587
      - SMTP_USER_NAME=plausible@services.aosus.org
      - SECRET_KEY_BASE
      - SMTP_USER_PWD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - MAXMIND_LICENSE_KEY
      - MAXMIND_EDITION=GeoLite2-City
    networks:
      default:
      web:

volumes:
  geoip:
    driver: local

configs:
  clickhouse-config:
    file: /home/aosus/plausible/clickhouse-config.xml
  clickhouse-user-config:
    file: /home/aosus/plausible/clickhouse-user-config.xml