networks:
  default:
  web:
    external: true
  discourse:
    external: true

services:
  web:
    image: ghcr.io/postalserver/postal:latest
    command: postal web-server
    restart: unless-stopped
    container_name: postal
    # ports:
    # - 127.0.0.1:5000:5000
    configs:
      - source: postal
        target: /config/postal.yml
      - source: signing-key
        target: /config/signing.key
    networks:
      - default
      - web
    depends_on: 
      - mariadb
      - rabbitmq

  smtp:
    image: ghcr.io/postalserver/postal:latest
    command: postal smtp-server
    restart: unless-stopped
    user: 0:0
    ports:
      - '25:25'
    cap_add: 
      - NET_BIND_SERVICE
    configs:
      - source: postal
        target: /config/postal.yml
      - source: signing-key
        target: /config/signing.key
        uid: "0"
        gid: "0"
    volumes:
      - caddy_data:/caddy-data:ro
    networks:
      - default
    depends_on: 
      - mariadb
      - rabbitmq

  worker:
    image: ghcr.io/postalserver/postal:latest
    restart: unless-stopped
    command: postal worker
    configs:
      - source: postal
        target: /config/postal.yml
      - source: signing-key
        target: /config/signing.key
    networks:
      - default
      - discourse
    depends_on: 
      - mariadb
      - rabbitmq

  cron:
    image: ghcr.io/postalserver/postal:latest
    restart: unless-stopped
    command: postal cron
    configs:
      - source: postal
        target: /config/postal.yml
      - source: signing-key
        target: /config/signing.key
    networks:
      - default
    depends_on: 
      - mariadb
      - rabbitmq

  requeuer:
    image: ghcr.io/postalserver/postal:latest
    restart: unless-stopped
    command: postal requeuer
    configs:
      - source: postal
        target: /config/postal.yml
      - source: signing-key
        target: /config/signing.key
    networks:
      - default
    depends_on: 
      - mariadb
      - rabbitmq

  runner:
    profiles: ["tools"]
    image: ghcr.io/postalserver/postal:latest
    restart: unless-stopped
    command: postal
    configs:
      - source: postal
        target: /config/postal.yml
      - source: signing-key
        target: /config/signing.key
    networks:
      - default
    depends_on: 
      - mariadb
      - rabbitmq

  spamassassin:
    # ports:
    #   - '127.0.0.1:783:783'
    restart: unless-stopped
    image: tiredofit/spamassassin:latest
    volumes:
      - spamassassin-data:/data
      - spamassassin-config:/config
      - spamassassin-logs:/logs
    networks: 
      - default

  clamav:
    image: mkodockx/docker-clamav:alpine
    restart: unless-stopped
    # ports:
    #   - '127.0.0.1:3310:3310'
    volumes:
      - clamav:/var/lib/clamav
    healthcheck:
      test: ["CMD", "./check.sh"]
      interval: 60s
      retries: 3
      start_period: 120s

  mariadb:
    # ports:
    #   - '127.0.0.1:3306:3306'
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=postal
      - MARIADB_ROOT_PASSWORD
      - MARIADB_AUTO_UPGRADE=true
    image: mariadb
    volumes:
      - /home/aosus/postal/mariadb:/var/lib/mysql
    networks: 
      - default

  rabbitmq:
    # ports:
    #   - '127.0.0.1:5672:5672'
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST=postal
    image: 'rabbitmq:3.8'
    networks: 
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

configs:
  postal:
    file: /home/aosus/postal/postal.yml
  signing-key:
    file: /home/aosus/postal/signing.key

volumes:
  clamav:
  spamassassin-data:
  spamassassin-config:
  spamassassin-logs:
  caddy_data:
    external: true