networks:
  discourse:
    external: true

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:13.0.1@sha256:b7ca099b2a527e03b0c2c71a6b6f3bc090ea9e1d378c5e1c4506bf9b6341e6d2
    container_name: mailserver
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: mail
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      # - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      # - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"  # POP3
      - "995:995"  # POP3 (with TLS)
    volumes:
      - mail-data:/var/mail
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
      - caddy_data:/caddy-data:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      discourse:

volumes:
  mail-data:
  mail-state:
  mail-logs:
  config:
  caddy_data:
    external: true