version: "3.7"

networks:
  web:
    external: true
  discourse:
    external: true

services:
  caddy:
    image: caddy:2.7.2-alpine@sha256:c65706cb6f36cd8ac2cf2ed7683e0bf3bc865019df07972ee011ffd875383235
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - /home/aosus/caddy/configs:/etc/caddy/configs:ro
      - data:/data
      - config:/config
      - piped-proxy:/var/run/ytproxy
    networks:
      web:
      discourse:
configs:
  Caddyfile:
    file: /home/aosus/caddy/Caddyfile

volumes:
  data:
  config:
  piped-proxy:
    external: 
      name: piped_piped-proxy