version: "3.7"

networks:
  web:
    external: true
  discourse:
    external: true

services:
  caddy:
    image: caddy:2.6.4-alpine@sha256:ca93629e04db8047dd93aa2bf1e66d24230146e83fc20034f5c210a895fd2f02
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - /home/aosus/caddy/configs:/etc/caddy/configs:ro
      - data:/data
      - config:/config
      - piped-proxy:/var/run/ytproxy
    networks:
      web:
      discourse:
configs:
  Caddyfile:
    file: /home/aosus/caddy/Caddyfile

volumes:
  data:
  config:
  piped-proxy:
    external: 
      name: piped_piped-proxy