version: "3.7"

networks:
  web:
    external: true
  discourse:
    external: true

services:
  caddy:
    image: caddy:2.6.4-alpine@sha256:eefd3d61e9ee8f35e046f614982d9a970006e3943c6e5f09957a4048f4c80d35
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - /home/aosus/caddy/configs:/etc/caddy/configs:ro
      - data:/data
      - config:/config
    networks:
      web:
      discourse:
    healthcheck:
      # https://ryanblunden.com/for-those-looking-for-a-http-health-check-in-alpine-images-wget-is-available-from-the-base-image-a07997be8699
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      # swarm zero-down time deployment
      update_config:
        delay: 5s
        order: start-first
        monitor: 30s
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

configs:
  Caddyfile:
    file: /home/aosus/caddy/Caddyfile

volumes:
  data:
  config: