version: '3.3'
networks:
  web:
    external: true

services:
  srcibe:
    container_name: scribe
    image: oci.fariszr.com/fariszr/scribe:latest@sha256:8e67aa08802dc2faff257a7bd12d1631c050a9f560a7010c2e19cb3ab3a632ed
    restart: always
    environment:
      - APP_DOMAIN=scribe.aosus.org
      #- DATABASE_URL=postgres://does@not/matter
      - LUCKY_ENV=production
      - PORT=8080
      #- SCRIBE_DB=postgres://does@not/matter
      #- SCRIBE_HOST=0.0.0.0
      #- SCRIBE_PORT=8080
      - SECRET_KEY_BASE
    networks:
      web:
