networks:
  web:
    external: true

services:
  scribe:
    container_name: scribe
    image: oci.fariszr.com/fariszr/scribe:latest@sha256:a00feae6b5868740bf448af5342b02b17f796e6e9bd00e63de90beaf12c32be8
    restart: always
    environment:
      - APP_DOMAIN=scribe.aosus.link
      - LUCKY_ENV=production
      - PORT=8080
      - SECRET_KEY_BASE
    networks:
      web:
