networks:
  default:
  telegram:
  web:
    external: true

services:
  postgres:
    image: postgres:14.9-alpine@sha256:df33047f21cb41298b51e17b9ac56a30362d5144d4bf9501d47aa768d59b6a9b
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/aosus/matrix/postgresql:/var/lib/postgresql/data:rw
    networks:
      default:


  synapse:
    image: ghcr.io/matrix-org/synapse:v1.91.0@sha256:b3de567afb549d0957632c2a9322551e5d5986ba6fdd535b52c95989f1873f01
    container_name: synapse
    restart: always
    volumes:
      - /home/aosus/matrix/media_store:/data/media_store:rw
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_CONFIG_DIR=config
    configs:
      - source: synapse-homeserver
        target: /config/homeserver.yaml
        uid: "991"
        gid: "991"
      - source: synapse-log-config
        target: /config/log.config
        uid: "991"
        gid: "991"
      - source: mautrix-telegram-appservice
        target: /app-services/telegram.yaml
        uid: "991"
        gid: "991"
      - source: matrix-hookshot-appservice
        target: /app-services/hookshot.yml
        uid: "991"
        gid: "991"
      - source: mautrix-discord-appservice
        target: /app-services/discord.yaml
        uid: "991"
        gid: "991"
    secrets:
      - source: matrix-signing-key
        target: signing.key
        uid: "991"
        gid: "991"
    healthcheck:
      test: [ "CMD", "curl", "-fSs", "http://localhost:8008/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      default:
      web:

  synapse-admin:
    container_name: synapse-admin
    image: awesometechnologies/synapse-admin:latest@sha256:2a4604582fe622581e238391c56849bf69f8c96a5a1359ae2ab18d3d3725ee33
    ports:
      - "100.68.206.74:8080:80"
    restart: unless-stopped

  mautrix-telegram:
    container_name: mautrix-telegram
    restart: always
    image: dock.mau.dev/mautrix/telegram:v0.14.1@sha256:5709a05cd10c3f3e8d7cbb8378db685406f05ba6f133a63807929605b560c1f8
    configs:
      - source: mautrix-telegram-appservice
        target: /data/registration.yaml
      - source: mautrix-telegram-config
        target: /data/config.yaml
    networks:
      default:

  postgres-telegram:
    image: postgres:14.9-alpine@sha256:df33047f21cb41298b51e17b9ac56a30362d5144d4bf9501d47aa768d59b6a9b
    restart: always
    environment:
      - POSTGRES_DB=telegram
      - POSTGRES_USER=telegram
      - POSTGRES_PASSWORD=${MATRIX_TELEGRAM_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/aosus/matrix/telegram/postgresql:/var/lib/postgresql/data:rw
    networks:
      default:

  mautrix-discord:
    container_name: mautrix-discord
    restart: always
    image: dock.mau.dev/mautrix/discord:latest@sha256:e9a61f3687939c100e281d9bc56993925339cf6f123fdc127458ea6e32ef21ab 
    configs:
      - source: mautrix-discord-appservice
        target: /data/registration.yaml
      - source: mautrix-discord-config
        target: /data/config.yaml

  postgres-discord:
    image: postgres:14.9-alpine@sha256:df33047f21cb41298b51e17b9ac56a30362d5144d4bf9501d47aa768d59b6a9b
    restart: always
    environment:
      - POSTGRES_DB=discord
      - POSTGRES_USER=discord
      - POSTGRES_PASSWORD=${MATRIX_DISCORD_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - discord-postgres:/var/lib/postgresql/data:rw

  matrix-hookshot:
    image: halfshot/matrix-hookshot:4.4.1@sha256:4784179b1e85a3729827e29971c77a328893f35b4852f94b2ce856799cb86307
    container_name: matrix-hookshot
    restart: always
    configs:
      - source: matrix-hookshot-appservice
        target: /data/registration.yml
      - source: matrix-hookshot-config
        target: /data/config.yml
    secrets:
      - source: matrix-hookshot-github-private-key
        target: github-key.pem
      - source: matrix-hookshot-pass-key
        target: passkey.pem
    expose:
      - 9993 # Homeserver appservice port
      - 9000 # Webhook port
      - 9002 # widgets port
    networks:
      web:
      default:


  coturn:
    image: coturn/coturn:4.6.2-alpine@sha256:cecbd85f5b27ce5bf00901192c9fe565c4be631f285411e5625427372a3a2f8b
    restart: always
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 48000-49200:48000-49200/udp
    environment:
      - min-port=48000
      - max-port=49200
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
      - source: coturn
        target: /etc/coturn/turnserver.conf

configs:
  synapse-homeserver:
    file: /home/aosus/matrix/homeserver.yaml
  synapse-log-config:
    file: /home/aosus/matrix/log.config
  mautrix-telegram-appservice:
    file: /home/aosus/matrix/mautrix-telegram/app-service-registration.yaml
  mautrix-telegram-config:
    file: /home/aosus/matrix/mautrix-telegram/config.yaml
  mautrix-discord-config:
    file: /home/aosus/matrix/mautrix-discord/config.yaml
  mautrix-discord-appservice:
    file: /home/aosus/matrix/mautrix-discord/app-service-registration.yaml
  matrix-hookshot-appservice:
    file: /home/aosus/matrix/matrix-hookshot/app-service-registration.yaml
  matrix-hookshot-config:
    file: /home/aosus/matrix/matrix-hookshot/config.yaml
  coturn:
    file: /home/aosus/matrix/turnserver.conf
# import secrets from environment variables set by the github runner
secrets:
  matrix-signing-key:
    environment: "MATRIX_SIGNING_KEY"
  matrix-hookshot-github-private-key:
    environment: "MATRIX_HOOKSHOT_GITHUB_PRIVATE_KEY"
  matrix-hookshot-pass-key:
    environment: "MATRIX_HOOKSHOT_PASS_KEY"

volumes:
  caddy_data:
    external: true
  discord-postgres: