networks:
  default:
    enable_ipv6: true
  web:
    external: true

services:
  postgres:
    image: postgres:14.9-alpine@sha256:874f566dd512d79cf74f59754833e869ae76ece96716d153b0fa3e64aec88d92
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/aosus/matrix/postgresql:/var/lib/postgresql/data:rw
    networks:
      default:


  synapse:
    image: ghcr.io/matrix-org/synapse:v1.95.0@sha256:a79ad98b73910fcc4f1cc21cbc958c6ac0a93910d83138814ba01b83885fb3ee
    container_name: synapse
    restart: always
    volumes:
      - /home/aosus/matrix/media_store:/data/media_store:rw
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_CONFIG_DIR=config
    configs:
      - source: synapse-homeserver
        target: /config/homeserver.yaml
        uid: "991"
        gid: "991"
      - source: synapse-log-config
        target: /config/log.config
        uid: "991"
        gid: "991"
      - source: mautrix-telegram-appservice
        target: /app-services/telegram.yaml
        uid: "991"
        gid: "991"
      - source: matrix-hookshot-appservice
        target: /app-services/hookshot.yml
        uid: "991"
        gid: "991"
      - source: mautrix-discord-appservice
        target: /app-services/discord.yaml
        uid: "991"
        gid: "991"
    secrets:
      - source: matrix-signing-key
        target: signing.key
        uid: "991"
        gid: "991"
    healthcheck:
      test: [ "CMD", "curl", "-fSs", "http://localhost:8008/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      default:
      web:

  synapse-admin:
    container_name: synapse-admin
    image: awesometechnologies/synapse-admin:latest@sha256:b617c4ce427817eb33befe95bcab6f259197f0de528de8c507c6bea27a5194cf
    ports:
      - "100.68.206.74:8080:80"
    restart: unless-stopped

  mautrix-telegram:
    container_name: mautrix-telegram
    restart: always
    image: dock.mau.dev/mautrix/telegram:v0.14.2@sha256:2ffe5e2ff47e1d9dca6fe998539cbacd47d7a8f82e0f8248d95637e4f1b3c743
    configs:
      - source: mautrix-telegram-appservice
        target: /data/registration.yaml
      - source: mautrix-telegram-config
        target: /data/config.yaml
    networks:
      default:

  postgres-telegram:
    image: postgres:14.9-alpine@sha256:874f566dd512d79cf74f59754833e869ae76ece96716d153b0fa3e64aec88d92
    restart: always
    environment:
      - POSTGRES_DB=telegram
      - POSTGRES_USER=telegram
      - POSTGRES_PASSWORD=${MATRIX_TELEGRAM_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/aosus/matrix/telegram/postgresql:/var/lib/postgresql/data:rw
    networks:
      default:

  mautrix-discord:
    container_name: mautrix-discord
    restart: always
    image: dock.mau.dev/mautrix/discord:latest@sha256:b89d8050cbdf6bd5d14a72b0b374390c04f18dfab0965ae2ec008a458560fa1e 
    configs:
      - source: mautrix-discord-appservice
        target: /data/registration.yaml
      - source: mautrix-discord-config
        target: /data/config.yaml

  postgres-discord:
    image: postgres:14.9-alpine@sha256:874f566dd512d79cf74f59754833e869ae76ece96716d153b0fa3e64aec88d92
    restart: always
    environment:
      - POSTGRES_DB=discord
      - POSTGRES_USER=discord
      - POSTGRES_PASSWORD=${MATRIX_DISCORD_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - discord-postgres:/var/lib/postgresql/data:rw

  matrix-hookshot:
    image: halfshot/matrix-hookshot:4.5.1@sha256:ceed583cefbac8e3fe2f8bbde3cce459fd9e90f1e72536aa4967ed5f34b4c3ac
    container_name: matrix-hookshot
    restart: always
    configs:
      - source: matrix-hookshot-appservice
        target: /data/registration.yml
      - source: matrix-hookshot-config
        target: /data/config.yml
    secrets:
      - source: matrix-hookshot-github-private-key
        target: github-key.pem
      - source: matrix-hookshot-pass-key
        target: passkey.pem
    expose:
      - 9993 # Homeserver appservice port
      - 9000 # Webhook port
      - 9002 # widgets port
    networks:
      web:
      default:


  eturnal:
    image: ghcr.io/processone/eturnal:1.12.0@sha256:c4ad43bc6a26d418455a0c89df9ce9850798c0a1401fc751ce43d831fd34e19b
    user: 0:0 # to access caddy certs
    ports:
      - '3478:3478'
      - '49000-49200:49000-49200'
      - '3478:3478/udp'
      - '49000-49200:49000-49200/udp'
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
      - source: eturnal
        target: /etc/eturnal.yml

  postgres-sync:
    image: postgres:15.4-alpine@sha256:35ce2187f2f7fb75e8e79493e13743596c21eb3789ff41ece145ae04d06e93a5
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=sync
      - POSTGRES_USER=sync
      - POSTGRES_PASSWORD=${MATRIX_SLIDING_SYNC_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - sliding-sync-postgres:/var/lib/postgresql/data
    networks:
      default:

  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:v0.99.11@sha256:42a1db931df998cd9603181d0ddaa9e69e9f963b91b597b71a25c1401b96ceeb
    restart: always
    environment:
      - SYNCV3_SERVER=https://matrix.aosus.org
      - SYNCV3_DB=${MATRIX_SLIDING_SYNC_POSTGRES_CONNECTION_STRING}
      - SYNCV3_SECRET=${MATRIX_SLIDING_SYNC_SECRET}
    depends_on:
      - postgres-sync
      - synapse
    networks:
      web:
      default:

configs:
  synapse-homeserver:
    file: /home/aosus/matrix/homeserver.yaml
  synapse-log-config:
    file: /home/aosus/matrix/log.config
  mautrix-telegram-appservice:
    file: /home/aosus/matrix/mautrix-telegram/app-service-registration.yaml
  mautrix-telegram-config:
    file: /home/aosus/matrix/mautrix-telegram/config.yaml
  mautrix-discord-config:
    file: /home/aosus/matrix/mautrix-discord/config.yaml
  mautrix-discord-appservice:
    file: /home/aosus/matrix/mautrix-discord/app-service-registration.yaml
  matrix-hookshot-appservice:
    file: /home/aosus/matrix/matrix-hookshot/app-service-registration.yaml
  matrix-hookshot-config:
    file: /home/aosus/matrix/matrix-hookshot/config.yaml
  eturnal:
    file: /home/aosus/matrix/eturnal.yml
# import secrets from environment variables set by the github runner
secrets:
  matrix-signing-key:
    environment: "MATRIX_SIGNING_KEY"
  matrix-hookshot-github-private-key:
    environment: "MATRIX_HOOKSHOT_GITHUB_PRIVATE_KEY"
  matrix-hookshot-pass-key:
    environment: "MATRIX_HOOKSHOT_PASS_KEY"

volumes:
  caddy_data:
    external: true
  discord-postgres:
  sliding-sync-postgres: