networks:
  default:
  telegram:
  web:
    external: true

services:
  postgres:
    image: postgres:14.7-alpine@sha256:07985c5c5e01ee550b30c67a2cf806f8b08b32f74e3f24c4cbef31305ef5776d
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/aosus/matrix/postgresql:/var/lib/postgresql/data:rw
    networks:
      default:


  synapse:
    image: ghcr.io/matrix-org/synapse:v1.83.0@sha256:84b96f0e79ff38827fc84307ed4104b39b4d569a18e0473ca579d7a482fa0b13
    container_name: synapse
    restart: always
    volumes:
      - /home/aosus/matrix/media_store:/data/media_store:rw
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_CONFIG_DIR=config
    configs:
      - source: synapse-homeserver
        target: /config/homeserver.yaml
        uid: "991"
        gid: "991"
      - source: synapse-log-config
        target: /config/log.config
        uid: "991"
        gid: "991"
      - source: mautrix-telegram-appservice
        target: /app-services/telegram.yaml
        uid: "991"
        gid: "991"
      - source: matrix-hookshot-appservice
        target: /app-services/hookshot.yml
        uid: "991"
        gid: "991"
      - source: matrix-discord-appservice
        target: /app-services/discord.yaml
        uid: "991"
        gid: "991"
    secrets:
      - source: matrix-signing-key
        target: signing.key
        uid: "991"
        gid: "991"
    healthcheck:
      test: [ "CMD", "curl", "-fSs", "http://localhost:8008/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      default:
      web:


  synapse-admin:
    container_name: synapse-admin
    image: awesometechnologies/synapse-admin:latest@sha256:3d67b18b8834419badf1d521bb2ceef2951e08810a1cd3b37d7369670b44026c
    ports:
      - "100.68.206.74:8080:80"
    restart: unless-stopped

  mautrix-telegram:
    container_name: mautrix-telegram
    restart: always
    image: dock.mau.dev/mautrix/telegram:v0.13.0@sha256:1060d5ce28a7013452801b6fae5eb93afc8055e6b5cac0b238cc045f8d14409a
    configs:
      - source: mautrix-telegram-appservice
        target: /data/registration.yaml
      - source: mautrix-telegram-config
        target: /data/config.yaml
    networks:
      default:
      telegram:


  postgres-telegram:
    image: postgres:14.7-alpine@sha256:07985c5c5e01ee550b30c67a2cf806f8b08b32f74e3f24c4cbef31305ef5776d
    restart: always
    environment:
      - POSTGRES_DB=telegram
      - POSTGRES_USER=telegram
      - POSTGRES_PASSWORD=${MATRIX_TELEGRAM_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /home/aosus/matrix/telegram/postgresql:/var/lib/postgresql/data:rw
    networks:
      telegram:

  mautrix-discord:
    container_name: mautrix-discord
    restart: always
    image: dock.mau.dev/mautrix/discord:v0.3.0@sha256:110bf290b38afc2565a6003274fb06dbb88491f7dcd8e92d7586ed0bb2840c09
    configs:
      - source: mautrix-discord-appservice
        target: /data/registration.yaml
      - source: mautrix-discord-config
        target: /data/config.yaml

  postgres-discord:
    image: postgres:14.7-alpine@sha256:07985c5c5e01ee550b30c67a2cf806f8b08b32f74e3f24c4cbef31305ef5776d
    restart: always
    environment:
      - POSTGRES_DB=discord
      - POSTGRES_USER=discord
      - POSTGRES_PASSWORD=${MATRIX_DISCORD_POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - discord-postgres:/var/lib/postgresql/data:rw

  matrix-hookshot:
    image: halfshot/matrix-hookshot:4.0.0@sha256:1b51ceb4d621fea793f2b7a33ae19178b2f84b7baa957805f31250021df86afd
    container_name: matrix-hookshot
    restart: always
    configs:
      - source: matrix-hookshot-appservice
        target: /data/registration.yml
      - source: matrix-hookshot-config
        target: /data/config.yml
    secrets:
      - source: matrix-hookshot-github-private-key
        target: github-key.pem
      - source: matrix-hookshot-pass-key
        target: passkey.pem
    expose:
      - 9993 # Homeserver appservice port
      - 9000 # Webhook port
      - 9002 # widgets port
    networks:
      web:
      default:


  coturn:
    image: coturn/coturn:4.6.2-alpine@sha256:e9eb2b7b8d24f4c23a53f6f98b7c59650283c6acc53c82f7daf534e2a9e3ac44
    restart: always
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 48000-49200:48000-49200/udp
    environment:
      - min-port=48000
      - max-port=49200
    volumes:
      - caddy_data:/caddy-data:ro
    configs:
      - source: coturn
        target: /etc/coturn/turnserver.conf

configs:
  synapse-homeserver:
    file: /home/aosus/matrix/homeserver.yaml
  synapse-log-config:
    file: /home/aosus/matrix/log.config
  mautrix-telegram-appservice:
    file: /home/aosus/matrix/mautrix-telegram/app-service-registration.yaml
  mautrix-telegram-config:
    file: /home/aosus/matrix/mautrix-telegram/config.yaml
  mautrix-discord-config:
    file: /home/aosus/matrix/mautrix-discord/config.yaml
  mautrix-discord-appservice:
    file: /home/aosus/matrix/mautrix-discord/app-service-registration.yaml
  matrix-hookshot-appservice:
    file: /home/aosus/matrix/matrix-hookshot/app-service-registration.yaml
  matrix-hookshot-config:
    file: /home/aosus/matrix/matrix-hookshot/config.yaml
  coturn:
    file: /home/aosus/matrix/turnserver.conf
# import secrets from environment variables set by the github runner
secrets:
  matrix-signing-key:
    environment: "MATRIX_SIGNING_KEY"
  matrix-hookshot-github-private-key:
    environment: "MATRIX_HOOKSHOT_GITHUB_PRIVATE_KEY"
  matrix-hookshot-pass-key:
    environment: "MATRIX_HOOKSHOT_PASS_KEY"

volumes:
  caddy_data:
    external: true
  discord-postgres: