networks:
  default:
  web:
    external: true

services:
  nextcloud:
    image: nextcloud:26.0.0-fpm-alpine@sha256:a4e0486f9f7b7149922dc7e59aab6fff6c8664559032c26acf169967db1b2fee
    command: sh -c "apk add --no-cache postgresql-client imagemagick procps samba-client; /entrypoint.sh php-fpm"
    restart: always
    volumes:
      - /home/aosus/nextcloud/html:/var/www/html:rw
      - /home/aosus/nextcloud/nextcloud-data:/var/www/html/data:rw
    configs:
      - source: nextcloud
        target: /var/www/html/config/env.config.php
    depends_on:
      - redis
      - postgresql
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.aosus.org
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD
      - POSTGRES_DB=ncdb
      - PHP_MEMORY_LIMIT=2G
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD
      - INSTANCE_ID
      # - NEXTCLOUD_ADMIN_USER
      # - NEXTCLOUD_ADMIN_PASSWORD
      - SMTP_HOST=smtp.eu.mailgun.org
      - SMTP_USER_NAME
      - SMTP_PASSWORD
      - SMTP_PORT=587
      - MAIL_ADDRESS=cloud
      - MAIL_DOMAIN=services.aosus.org
      - PASSWORD_SALT
      - SECRET

  postgresql:
    hostname: postgresql
    image: postgres:15.2-alpine@sha256:ab88acc4edfbd7c728ad0fa741139b6cc830bd85138a40848672b784aab57306
    restart: always
    volumes:
      - /home/aosus/nextcloud/postgresql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=ncdb

  redis:
    image: redis:7.0.10-alpine@sha256:221f7fa5b4c563971358755893263d64b0b52e9798f6320f2898be499fb3b6b6
    # container_name: nextcloud_redis
    # user: "1000:1000"
    restart: always
    tmpfs:
      - /var/lib/redis
    configs:
      - source: nextcloud
        target: /var/www/html/config/env.config.php
    environment:
      - REDIS_HOST_PASSWORD
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}

  nginx:
    image: nginx:1.23.4-alpine@sha256:c94a22b036afa972426b82d5b0a49c959786005b4f6f81ac7467ca5538d0158f
    restart: always
    container_name: nextcloud_web
    configs:
      - source: nextcloud
        target: /var/www/html/config/env.config.php
      - source: nginx
        target: /etc/nginx/nginx.conf
    volumes:
      - /home/aosus/nextcloud/html:/var/www/html:ro
    depends_on:
      - nextcloud
    networks:
      web:
      default:

  cron:
    image: nextcloud:26.0.0-fpm-alpine@sha256:a4e0486f9f7b7149922dc7e59aab6fff6c8664559032c26acf169967db1b2fee
    restart: always
    command: sh -c "apk add --no-cache postgresql-client imagemagick procps samba-client; /cron.sh"
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.aosus.org
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD
      - POSTGRES_DB=ncdb
      - PHP_MEMORY_LIMIT=2G
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD
      - INSTANCE_ID
      # - NEXTCLOUD_ADMIN_USER
      # - NEXTCLOUD_ADMIN_PASSWORD
      - SMTP_HOST=mailer.aosus.org
      - SMTP_USER_NAME
      - SMTP_PASSWORD
      - MAIL_ADDRESS=cloud
      - MAIL_DOMAIN=services.aosus.org
      - PASSWORD_SALT
      - SECRET
    configs:
      - source: nextcloud
        target: /var/www/html/config/env.config.php
    volumes:
      - /home/aosus/nextcloud/html:/var/www/html:rw
      - /home/aosus/nextcloud/nextcloud-data:/var/www/html/data:rw
    entrypoint: /cron.sh
    depends_on:
      - redis
      - postgresql

  clamav:
    image: mkodockx/docker-clamav:alpine@sha256:40c97633be145a03f115e36e53b5bd9bbb4814d8e70d54fa34752eada41df8da
    container_name: clamav
    restart: unless-stopped
    # ports:
    #   - '127.0.0.1:3310:3310'
    volumes:
      - clamav:/var/lib/clamav
    healthcheck:
      test: [ "CMD", "/home/aosus/nextcloud/check.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s

  collabora:
    image: collabora/code:22.05.12.4.1@sha256:c0c1317a0fda872fce547f99a893041e282e65608d2a12287824ca43bf573789
    container_name: nextcloud-collabora
    restart: always
    expose:
      - 9980
    environment:
      - 'domain=cloud.aosus.org'
      - 'dictionaries=ar'
    cap_add:
      - MKNOD
    tty: true
    networks:
      default:
      web:

configs:
  nextcloud:
    file: /home/aosus/nextcloud/env.config.php
  nginx:
    file: /home/aosus/nextcloud/nginx.conf

volumes:
  clamav: