networks:
  default:
  web:
    external: true

services:
  nextcloud:
    image: nextcloud:fpm-alpine
    command: sh -c "apk add --no-cache postgresql-client imagemagick procps samba-client; /entrypoint.sh php-fpm"
    restart: always
    volumes:
      - /home/aosus/nextcloud/html:/var/www/html:rw
      - /home/aosus/nextcloud/nextcloud-data:/var/www/html/data:rw
    configs:
      - source: nextcloud
        target: /var/www/html/config/config.php
    depends_on:
      - redis
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.aosus.org
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD
      - POSTGRES_DB=ncdb
      - PHP_MEMORY_LIMIT=2G
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD
      - INSTANCE_ID
      # - NEXTCLOUD_ADMIN_USER
      # - NEXTCLOUD_ADMIN_PASSWORD
      - SMTP_HOST=mailer.aosus.org
      - SMTP_USER_NAME
      - SMTP_PASSWORD
      - MAIL_ADDRESS=cloud
      - MAIL_DOMAIN=services.aosus.org
      - PASSWORD_SALT
      - SECRET

  postgresql:
    hostname: postgresql
    image: postgres:13-alpine
    restart: always
    configs:
      - source: nextcloud
        target: /var/www/html/config/config.php
    volumes:
      - /home/aosus/nextcloud/postgresql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=ncdb

  redis:
    image: redis:alpine
    # container_name: nextcloud_redis
    # user: "1000:1000"
    restart: always
    tmpfs:
      - /var/lib/redis
    configs:
      - source: nextcloud
        target: /var/www/html/config/config.php
    environment:
      - REDIS_HOST_PASSWORD
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nextcloud_web
    configs:
      - source: nextcloud
        target: /var/www/html/config/config.php
      - source: nginx
        target: /etc/nginx/nginx.conf
    volumes:
      - /home/aosus/nextcloud/html:/var/www/html:ro
    depends_on:
      - nextcloud
    networks:
      web:
      default:

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    command: sh -c "apk add --no-cache postgresql-client imagemagick procps samba-client; /cron.sh"
    configs:
      - source: nextcloud
        target: /var/www/html/config/config.php
    volumes:
      - /home/aosus/nextcloud/html:/var/www/html:rw
      - /home/aosus/nextcloud/nextcloud-data:/var/www/html/data:rw
    entrypoint: /cron.sh
    depends_on:
      - redis

  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    restart: unless-stopped
    # ports:
    #   - '127.0.0.1:3310:3310'
    volumes:
      - clamav:/var/lib/clamav
    healthcheck:
      test: [ "CMD", "/home/aosus/nextcloud/check.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s

  collabora:
    image: collabora/code
    container_name: nextcloud-collabora
    restart: always
    expose:
      - 9980
    environment:
      - 'domain=cloud.aosus.org'
      - 'dictionaries=ar'
    cap_add:
      - MKNOD
    tty: true
    networks:
      default:
      web:

configs:
  nextcloud:
    file: /home/aosus/nextcloud/config.php
  nginx:
    file: /home/aosus/nextcloud/nginx.conf

volumes:
  clamav: