networks:
  web:
    external: true
  default:

services:
  postgresql:
    hostname: postgresql
    image: postgres:12.14-alpine@sha256:a8be70f5cbf8a4dd5aa5763f8e9134cf150597e1df2059490f380c34d8db3f5f
    restart: always
    volumes:
      - /home/aosus/authentik/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}

  redis:
    hostname: redis
    image: redis:7.0.10-alpine@sha256:0859ed47321d2d26a3f53bca47b76fb7970ea2512ca3a379926dc965880e442e
    restart: always

  server:
    image: ghcr.io/goauthentik/server:2023.3@sha256:853d73ed2670715c45da2e7d92fa9a53d3efba5b275d1ad395ed961a003932ea
    container_name: authentik
    restart: always
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS}
      - AUTHENTIK_EMAIL__USERNAME
      - AUTHENTIK_EMAIL__PASSWORD
      - AUTHENTIK_SECRET_KEY
      - AUTHENTIK_ERROR_REPORTING__ENABLED="true"
      - AUTHENTIK_EMAIL__PORT
      - AUTHENTIK_EMAIL__HOST
      - AUTHENTIK_EMAIL__USE_TLS=true
      - AUTHENTIK_EMAIL__USE_SSL=false
      - AUTHENTIK_EMAIL__TIMEOUT=10
      - AUTHENTIK_EMAIL__FROM
      # WORKERS: 2
    volumes:
      - /home/aosus/authentik/media:/media
      - /home/aosus/authentik/custom-templates:/templates
    networks:
      web:
      default:

  worker:
    image: ghcr.io/goauthentik/server:2023.3@sha256:853d73ed2670715c45da2e7d92fa9a53d3efba5b275d1ad395ed961a003932ea
    restart: always
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=${PG_USER}
      - AUTHENTIK_POSTGRESQL__NAME=${PG_DB}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS}
      - AUTHENTIK_EMAIL__USERNAME
      - AUTHENTIK_EMAIL__PASSWORD
      - AUTHENTIK_SECRET_KEY
      - AUTHENTIK_ERROR_REPORTING__ENABLED="true"
      - AUTHENTIK_EMAIL__PORT
      - AUTHENTIK_EMAIL__HOST
      - AUTHENTIK_EMAIL__USE_TLS=true
      - AUTHENTIK_EMAIL__USE_SSL=false
      - AUTHENTIK_EMAIL__TIMEOUT=10
      - AUTHENTIK_EMAIL__FROM
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /backups and /media folders aren't fixed, so make sure they are 1000:1000
    volumes:
      - /home/aosus/authentik/backups:/backups
      - /home/aosus/authentik/media:/media
      - /home/aosus/authentik/custom-templates:/templates
