version: '3.3'

services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    userns_mode: 'host' # server uses docker-ns, use 
    environment:
      - WATCHTOWER_NOTIFICATIONS_LEVEL=error # only send errors
      - WATCHTOWER_NOTIFICATION_URL
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=hyper-aosus
      - WATCHTOWER_CLEANUP=true # cleanup old images after updates
      - WATCHTOWER_SCHEDULE=* * 21 ? * * # check for update at 12AM UTC+3
      - WATCHTOWER_ROLLING_RESTART=true # Restart one image at time instead of stopping and starting all at once
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_TIMEOUT=40s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro # use time zone of the server