networks: 
  default:
    enable_ipv6: true
  web:
    external: true

services:
  wordpress:
    image: wordpress:6.4.3-apache@sha256:fbd2cd8894fc592b2c4d5a90f707933e752b9523a48a1906abd6f89daff79981
    container_name: aosus-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: aosusworddb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      # WORDPRESS_DEBUG: true
    networks: 
      default:
      web:
    volumes:
      - /home/aosus/aosus-wordpress/html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:11.2.3@sha256:4d17158efa6f92bb9894c048c87d784758e20b9a3c1956ad3a1f1f2292d2b7c3
    restart: always
    environment:
      MARIADB_USER: aosusworddb
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD:
      MARIADB_AUTO_UPGRADE: true
      #MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_ROOT_PASSWORD:
    volumes:
      - /home/aosus/aosus-wordpress/mariadb:/var/lib/mysql

configs:
  custom-ini:
    file: /home/aosus/aosus-wordpress/custom.ini
