networks: 
  default:
    enable_ipv6: true
  web:
    external: true

services:
  wordpress:
    image: wordpress:6.4.3-apache@sha256:9ec6fd955130050c02c1c218a8c63f2f1d8c5552d1ed6d9de1465a57cfdf500a
    container_name: aosus-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: aosusworddb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      # WORDPRESS_DEBUG: true
    networks: 
      default:
      web:
    volumes:
      - /home/aosus/aosus-wordpress/html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:11.2.2@sha256:fee2ec0d2b4f15f21aa1f88305d4085fdc0a9bb7242a1b4409f3002c6160d05b
    restart: always
    environment:
      MARIADB_USER: aosusworddb
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD:
      MARIADB_AUTO_UPGRADE: true
      #MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_ROOT_PASSWORD:
    volumes:
      - /home/aosus/aosus-wordpress/mariadb:/var/lib/mysql

configs:
  custom-ini:
    file: /home/aosus/aosus-wordpress/custom.ini
