networks: 
  default:
  web:
    external: true

services:
  wordpress:
    image: wordpress:6.2.2-apache@sha256:134c8f422e96a9c9528e9ee1783cc3cbf001aa419846c7a16d866d7131692b0a
    container_name: aosus-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: aosusworddb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      # WORDPRESS_DEBUG: true
    networks: 
      default:
      web:
    volumes:
      - /home/aosus/aosus-wordpress/html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:10.11.4@sha256:bc54c570d4f90e14ec614dc83ad7b0b03c678caba628ad3a783e313d2d69842e
    restart: always
    environment:
      MARIADB_USER: aosusworddb
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD:
      MARIADB_AUTO_UPGRADE: true
      #MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_ROOT_PASSWORD:
    volumes:
      - /home/aosus/aosus-wordpress/mariadb:/var/lib/mysql

configs:
  custom-ini:
    file: /home/aosus/aosus-wordpress/custom.ini