version: '3.1'

networks: 
  default:
  web:
    external: true

services:
  wordpress:
    image: wordpress:php7.4@sha256:7e46cf3373751b6d62b7a0fc3a7d6686f641a34a2a0eb18947da5375c55fd009
    container_name: gnulinuxsa-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
    networks: 
      default:
      web:
    volumes:
      - /home/aosus/gnulinuxsa-wordpress/html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:11.0.2@sha256:c9520bf76a3cdad4779d65bae4c6c46278283a7212511d99a06c90480d42efb4
    restart: always
    environment:
      MARIADB_USER: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD:
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_AUTO_UPGRADE: true
    volumes:
      - /home/aosus/gnulinuxsa-wordpress/mariadb:/var/lib/mysql:rw

configs:
  custom-ini:
    file: /home/aosus/gnulinuxsa-wordpress/custom.ini