name: deploy-authentik

on:
  push:
    paths:
      - '.github/workflows/authentik.yml'
      - 'authentik/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@ce41a99162202a647a4b24c30c558a567b926709
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: Github-actions
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1
        env:
          PG_USER: ${{ secrets.authentik_pg_user }}
          PG_DB: ${{ secrets.authentik_pg_db }}
          PG_PASS: ${{ secrets.authentik_pg_pass }}
          AUTHENTIK_EMAIL_USERNAME: ${{ secrets.authentik_email_username }}
          AUTHENTIK_EMAIL_PASSWORD: ${{ secrets.authentik_email_password }}
          AUTHENTIK_SECRET_KEY: ${{ secrets.authentik_secret_key }}
          AUTHENTIK_EMAIL__PORT: ${{ secrets.authentik_email__port }}
          AUTHENTIK_EMAIL__HOST: ${{ secrets.authentik_email__host }}
          AUTHENTIK_EMAIL__FROM: ${{ secrets.authentik_email__from }}
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          compose_file_path: authentik/docker-compose.yml
          args: -p authentik up -d --remove-orphans