name: deploy-caddy

on:
  push:
    paths:
      - '.github/workflows/caddy.yml'
      - 'caddy/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@7bd8039bf25c23c4ab1b8d6e2cc2da2280601966
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: Github-actions
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1
        env:
          EMAIL: ${{ secrets.email }}
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          compose_file_path: caddy/docker-compose.yml
          args: -p caddy up -d --remove-orphans
          upload_directory: true
          docker_compose_directory: caddy