name: deploy-piped

on:
  push:
    paths:
      - '.github/workflows/piped.yml'
      - 'piped/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: piped
      url: https://piped.aosus.link
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@7bd8039bf25c23c4ab1b8d6e2cc2da2280601966
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: Github-actions
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Add secrets to config files
        env:
          POSTGRES_PASSWORD: ${{ secrets.piped_postgres_password }}
        run: |
          sed -i "s/(piped_postgres_password)/$POSTGRES_PASSWORD/g" $GITHUB_WORKSPACE/piped/config.properties

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1
        env:
          POSTGRES_PASSWORD: ${{ secrets.piped_postgres_password }}
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          upload_directory: true # upload docker directory
          docker_compose_directory: piped # directory to upload
          compose_file_path: piped/docker-compose.yml
          args: -p piped up -d --remove-orphans